### ISSUE TITLE
Error while importing packagе

### ISSUE THREAD

**Issue by mpstv** [emirdeliz/diff-json-keys#1]
Hello! I found the issue.

Step to reproduce:
1. Install package: `npm i diff-json-keys`
2. Import package: `import { runDiff } from "diff-json-keys";`
3. Run script and get error: `Error: Cannot find package` with code `code: 'ERR_MODULE_NOT_FOUND'`

I'm not sure, but maybe it's because [index.js specify as main file](https://github.com/emirdeliz/diff-json-keys/blob/main/package.json#L6), but not exist in the repository.

**Comment by emirdeliz** [comment]
I fixed it in version [1.0.3](https://www.npmjs.com/package/diff-json-keys).

**Comment by mpstv** [comment]
Unfortunately, error still reproduces.

I'm not very good knowing about npm packages, but if navigate to `node_modules` after install package, may see only ts files. Its looks like source code is not compiled. Also main file link in package.json not correct.

**Comment by mpstv** [comment]
Also it seems all package [dependencies](https://github.com/emirdeliz/diff-json-keys/blob/main/package.json#L23) can be specified as dev.

**Comment by emirdeliz** [comment]
@mpstv, sorry for my mistake. I fixed it in version 1.0.11

**Comment by mpstv** [comment]
yes, now imports work.

Thank you!
